### ISSUE TITLE
use one name: googlesearch or google?

### ISSUE THREAD

**Issue by blshkv** [MarioVilas/googlesearch#109]
could you sync up and use googlesearch everywhere?
to be fixed: 

- https://pypi.org/project/google/
- https://github.com/MarioVilas/googlesearch/blob/master/scripts/google

may be more

**Comment by MarioVilas** [comment]
Hi!

I don't think I can rename the PyPi project. As far as I know that was never an option, I could maybe delete the project and recreate it but to be honest I have no idea if that would be wise (I've had very bad experiences with PyPi in the past, so nowadays I treat it with a "if it ain't broke don't fix it" philosophy).

As for the second link, the package name is "googlesearch" but the script is called "google" and this is intentional. The script is only launched from the command line and does not affect the Python module itself.

As far as I know there are no more instances of the old package name.

Cheers!

**Comment by blshkv** [comment]
The name is to generic and I'm sure it will overlap another project which aslo installed '''/usr/bin/google'''

**Comment by MarioVilas** [comment]
Are there any?

**Comment by blshkv** [comment]
No idea. Im not going to try all software in the world ;) and even if there are none, somebody can release it tomorrow

**Comment by MarioVilas** [comment]
Then let them complain when that happens :D
